from .aitemplate import AITemplateModelManager
from .base import BaseModelManager
from .blip import BlipModelManager
from .clip import ClipModelManager
from .codeformer import CodeFormerModelManager
from .compvis import CompVisModelManager
from .esrgan import EsrganModelManager
from .gfpgan import GfpganModelManager
from .super import ModelManager
